<?php namespace Database\Seeds;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class BreedClassificationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //delete breeds table records
        DB::table('breed_classification')->delete();

        //insert some gender type records
         DB::table('breed_classification')->insert(array(
            array('breed_id' => 1, 'classification_id' => 18),
            array('breed_id' => 2, 'classification_id' => 1),
            array('breed_id' => 3, 'classification_id' => 3),
            array('breed_id' => 3, 'classification_id' => 12),
            array('breed_id' => 4, 'classification_id' => 3),
            array('breed_id' => 4, 'classification_id' => 12),
            array('breed_id' => 5, 'classification_id' => 17),
            array('breed_id' => 6, 'classification_id' => 10),
            array('breed_id' => 6, 'classification_id' => 14),
            array('breed_id' => 7, 'classification_id' => 9),
            array('breed_id' => 8, 'classification_id' => 2),
            array('breed_id' => 8, 'classification_id' => 12),
            array('breed_id' => 9, 'classification_id' => 16),
            array('breed_id' => 10, 'classification_id' => 5),
            array('breed_id' => 11, 'classification_id' => 13),
            array('breed_id' => 12, 'classification_id' => 15),
            array('breed_id' => 13, 'classification_id' => 4),
            array('breed_id' => 13, 'classification_id' => 15),
            array('breed_id' => 14, 'classification_id' => 1),
            array('breed_id' => 14, 'classification_id' => 14),
            array('breed_id' => 15, 'classification_id' => 17),
            array('breed_id' => 16, 'classification_id' => 17),
            array('breed_id' => 17, 'classification_id' => 15),
            array('breed_id' => 18, 'classification_id' => 19),
            array('breed_id' => 19, 'classification_id' => 18),
            array('breed_id' => 20, 'classification_id' => 5),
            array('breed_id' => 20, 'classification_id' => 12),
            array('breed_id' => 21, 'classification_id' => 16),
            array('breed_id' => 22, 'classification_id' => 12),
            array('breed_id' => 23, 'classification_id' => 17),
            array('breed_id' => 24, 'classification_id' => 1),
            array('breed_id' => 25, 'classification_id' => 18),
            array('breed_id' => 26, 'classification_id' => 4),
            array('breed_id' => 26, 'classification_id' => 15),
            array('breed_id' => 27, 'classification_id' => 2),
            array('breed_id' => 27, 'classification_id' => 14),
            array('breed_id' => 28, 'classification_id' => 17),
            array('breed_id' => 29, 'classification_id' => 7),
            array('breed_id' => 30, 'classification_id' => 9),
            array('breed_id' => 31, 'classification_id' => 1),
            array('breed_id' => 31, 'classification_id' => 12),
            array('breed_id' => 32, 'classification_id' => 1),
            array('breed_id' => 32, 'classification_id' => 13),
            array('breed_id' => 33, 'classification_id' => 2),
            array('breed_id' => 33, 'classification_id' => 13),
            array('breed_id' => 33, 'classification_id' => 12),
            array('breed_id' => 34, 'classification_id' => 12),
            array('breed_id' => 35, 'classification_id' => 19),
            array('breed_id' => 37, 'classification_id' => 16),
            array('breed_id' => 38, 'classification_id' => 7),
            array('breed_id' => 38, 'classification_id' => 15),
            array('breed_id' => 39, 'classification_id' => 8),
            array('breed_id' => 39, 'classification_id' => 11),
            array('breed_id' => 40, 'classification_id' => 12),
            array('breed_id' => 41, 'classification_id' => 1),
            array('breed_id' => 41, 'classification_id' => 12),
            array('breed_id' => 42, 'classification_id' => 1),
            array('breed_id' => 42, 'classification_id' => 12),
            array('breed_id' => 43, 'classification_id' => 5),
            array('breed_id' => 43, 'classification_id' => 13),
            array('breed_id' => 44, 'classification_id' => 1),
            array('breed_id' => 44, 'classification_id' => 12),
            array('breed_id' => 45, 'classification_id' => 7),
            array('breed_id' => 45, 'classification_id' => 14),
            array('breed_id' => 46, 'classification_id' => 7),
            array('breed_id' => 46, 'classification_id' => 14),
            array('breed_id' => 47, 'classification_id' => 5),
            array('breed_id' => 47, 'classification_id' => 12),
            array('breed_id' => 48, 'classification_id' => 4),
            array('breed_id' => 48, 'classification_id' => 15),
            array('breed_id' => 49, 'classification_id' => 3),
            array('breed_id' => 49, 'classification_id' => 12),
            array('breed_id' => 49, 'classification_id' => 13),
            array('breed_id' => 50, 'classification_id' => 18),
            array('breed_id' => 51, 'classification_id' => 9),
            array('breed_id' => 51, 'classification_id' => 14),
            array('breed_id' => 52, 'classification_id' => 19),
            array('breed_id' => 53, 'classification_id' => 3),
            array('breed_id' => 53, 'classification_id' => 12),
            array('breed_id' => 54, 'classification_id' => 8),
            array('breed_id' => 55, 'classification_id' => 16),
            array('breed_id' => 56, 'classification_id' => 10),
            array('breed_id' => 56, 'classification_id' => 12),
            array('breed_id' => 57, 'classification_id' => 1),
            array('breed_id' => 57, 'classification_id' => 12),
            array('breed_id' => 58, 'classification_id' => 2),
            array('breed_id' => 58, 'classification_id' => 12),
            array('breed_id' => 59, 'classification_id' => 8),
            array('breed_id' => 59, 'classification_id' => 11),
            array('breed_id' => 60, 'classification_id' => 16),
            array('breed_id' => 61, 'classification_id' => 1),
            array('breed_id' => 61, 'classification_id' => 12),
            array('breed_id' => 62, 'classification_id' => 9),
            array('breed_id' => 62, 'classification_id' => 12),
            array('breed_id' => 63, 'classification_id' => 6),
            array('breed_id' => 63, 'classification_id' => 14),
            array('breed_id' => 64, 'classification_id' => 17),
            array('breed_id' => 65, 'classification_id' => 2),
            array('breed_id' => 65, 'classification_id' => 13),
            array('breed_id' => 66, 'classification_id' => 1),
            array('breed_id' => 67, 'classification_id' => 1),
            array('breed_id' => 67, 'classification_id' => 12),
            array('breed_id' => 67, 'classification_id' => 13),
            array('breed_id' => 68, 'classification_id' => 16),
            array('breed_id' => 69, 'classification_id' => 17),
            array('breed_id' => 70, 'classification_id' => 16),
            array('breed_id' => 71, 'classification_id' => 17),
            array('breed_id' => 72, 'classification_id' => 13),
            array('breed_id' => 73, 'classification_id' => 4),
            array('breed_id' => 73, 'classification_id' => 14),
            array('breed_id' => 74, 'classification_id' => 3),
            array('breed_id' => 74, 'classification_id' => 12),
            array('breed_id' => 75, 'classification_id' => 15),
            array('breed_id' => 76, 'classification_id' => 10),
            array('breed_id' => 76, 'classification_id' => 12),
            array('breed_id' => 77, 'classification_id' => 9),
            array('breed_id' => 77, 'classification_id' => 12),
            array('breed_id' => 78, 'classification_id' => 2),
            array('breed_id' => 78, 'classification_id' => 12),
            array('breed_id' => 79, 'classification_id' => 17),
            array('breed_id' => 80, 'classification_id' => 16),
            array('breed_id' => 81, 'classification_id' => 18),
            array('breed_id' => 82, 'classification_id' => 5),
            array('breed_id' => 82, 'classification_id' => 12),
            array('breed_id' => 83, 'classification_id' => 3),
            array('breed_id' => 83, 'classification_id' => 12),
            array('breed_id' => 84, 'classification_id' => 1),
            array('breed_id' => 84, 'classification_id' => 13),
            array('breed_id' => 85, 'classification_id' => 9),
            array('breed_id' => 85, 'classification_id' => 14)
        ));
    }
}
