<?php namespace Database\Seeds;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class VarietiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	//delete varieties table records
        DB::table('varieties')->delete();

        //insert the varieties
        DB::table('varieties')->insert(array(
		array('variety' => 'American'),
		array('variety' => 'Barred'),
		array('variety' => 'Bearded Black'),
		array('variety' => 'Bearded Blue'),
		array('variety' => 'Bearded Buff'),
		array('variety' => 'Bearded Buff Laced'),
		array('variety' => 'Bearded Gray'),
		array('variety' => 'Bearded Golden'),
		array('variety' => 'Bearded Golden Neck'),
		array('variety' => 'Bearded Mille Fleur'),
		array('variety' => 'Bearded Mottled'),
		array('variety' => 'Bearded Partridge'),
		array('variety' => 'Bearded Porcelain'),
		array('variety' => 'Bearded Self Blue'),
		array('variety' => 'Bearded Silver'),
		array('variety' => 'Bearded Splash'),
		array('variety' => 'Bearded White'),
		array('variety' => 'Beltsville Small White'),
		array('variety' => 'Birchen'),
		array('variety' => 'Black'),
		array('variety' => 'Black Frizzle'),
		array('variety' => 'Black & White'),
		array('variety' => 'Black Breasted Red'),
		array('variety' => 'Black Tailed Buff'),
		array('variety' => 'Black Tailed Red'),
		array('variety' => 'Blue'),
		array('variety' => 'Blue & White'),
		array('variety' => 'Blue Brassy Back'),
		array('variety' => 'Blue Breasted Red'),
		array('variety' => 'Blue Cream Light Brown'),
		array('variety' => 'Blue Golden Duckwing'),
		array('variety' => 'Blue Laced Red'),
		array('variety' => 'Blue Light Brown Dutch'),
		array('variety' => 'Blue Silver Duckwing'),
		array('variety' => 'Blue Wheaten'),
		array('variety' => 'Bourbon Red'),
		array('variety' => 'Butterscotch'),
		array('variety' => 'Brassy Back'),
		array('variety' => 'Bronze'),
		array('variety' => 'Brown'),
		array('variety' => 'Brown Red'),
		array('variety' => 'Buff'),
		array('variety' => 'Buff Columbian'),
		array('variety' => 'Chocolate'),
		array('variety' => 'Colored'),
		array('variety' => 'Columbian'),
		array('variety' => 'Cream Light Brown'),
		array('variety' => 'Crele'),
		array('variety' => 'Cuckoo'),
		array('variety' => 'Cumberland Blue'),
		array('variety' => 'Dark'),
		array('variety' => 'Dark Brown'),
		array('variety' => 'Eastern'),
		array('variety' => 'Fawn & White'),
		array('variety' => 'Fawn Silver Duckwing'),
		array('variety' => 'Ginger Red'),
		array('variety' => 'Golden'),
		array('variety' => 'Golden Duckwing'),
		array('variety' => 'Golden Penciled'),
		array('variety' => 'Golden Laced'),
		array('variety' => 'Golden Spangled'),
		array('variety' => 'Gray'),
		array('variety' => 'Khaki'),
		array('variety' => 'Lavender'),
		array('variety' => 'Lemon Blue'),
		array('variety' => 'Light'),
		array('variety' => 'Light Brown'),
		array('variety' => 'Partridge'),
		array('variety' => 'Pastel'),
		array('variety' => 'Pearl'),
		array('variety' => 'Penciled'),
		array('variety' => 'Porcelain'),
		array('variety' => 'Narragansett'),
		array('variety' => 'Mille Fleur'),
		array('variety' => 'Mottled'),
		array('variety' => 'Non Bearded Black'),
		array('variety' => 'Non Bearded Blue'),
		array('variety' => 'Non Bearded Buff'),
		array('variety' => 'Non Bearded Buff Laced'),
		array('variety' => 'Non Bearded Gray'),
		array('variety' => 'Non Bearded Golden'),
		array('variety' => 'Non Bearded Partridge'),
		array('variety' => 'Non Bearded Silver'),
		array('variety' => 'Non Bearded White'),
		array('variety' => 'Non Bearded White Crested Black'),
		array('variety' => 'Non Bearded White Crested Blue'),
		array('variety' => 'Non Bearded Black Crested White'),
		array('variety' => 'Quail'),
		array('variety' => 'Red'),
		array('variety' => 'Red Pyle'),
		array('variety' => 'Red Shouldered'),
		array('variety' => 'Rose Comb'),
		array('variety' => 'Rose Comb Black'),
		array('variety' => 'Rose Comb Buff'),
		array('variety' => 'Rose Comb Cuckoo'),
		array('variety' => 'Rose Comb Golden'),
		array('variety' => 'Rose Comb Silver'),
		array('variety' => 'Rose Comb White'),
		array('variety' => 'Royal Palm'),
		array('variety' => 'Saddleback'),
		array('variety' => 'Salmon'),
		array('variety' => 'Self Blue'),
		array('variety' => 'Sex Linked'),
		array('variety' => 'Silver'),
		array('variety' => 'Silver Blue'),
		array('variety' => 'Silver Duckwing'),
		array('variety' => 'Silver Gray'),
		array('variety' => 'Silver Laced'),
		array('variety' => 'Silver Penciled'),
		array('variety' => 'Silver Spangled'),
		array('variety' => 'Single Comb'),
		array('variety' => 'Single Comb Black'),
		array('variety' => 'Single Comb Black Tailed Red'),
		array('variety' => 'Single Comb Buff'),
		array('variety' => 'Single Comb Columbian'),
		array('variety' => 'Single Comb Cuckoo'),
		array('variety' => 'Single Comb Dark Brown'),
		array('variety' => 'Single Comb Light Brown'),
		array('variety' => 'Single Comb Red'),
		array('variety' => 'Single Comb Silver'),
		array('variety' => 'Slate'),
		array('variety' => 'Snowy'),
		array('variety' => 'Speckled'),
		array('variety' => 'Tufted'),
		array('variety' => 'Wheaten'),
		array('variety' => 'White'),
		array('variety' => 'White Holland'),
		array('variety' => 'White Laced Red')
        ));
    }
}
