<?php

use Illuminate\Database\Seeder;

class VarietiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('varieties')->insert([
		'variety' => 'American',
		'variety' => 'Barred',
		'variety' => 'Bearded Black',
		'variety' => 'Bearded Blue',
		'variety' => 'Bearded Buff',
		'variety' => 'Bearded Buff Laced',
		'variety' => 'Bearded Gray',
		'variety' => 'Bearded Golden',
		'variety' => 'Bearded Golden Neck',
		'variety' => 'Bearded Mille Fleur',
		'variety' => 'Bearded Mottled',
		'variety' => 'Bearded Partridge',
		'variety' => 'Bearded Porcelain',
		'variety' => 'Bearded Self Blue',
		'variety' => 'Bearded Silver',
		'variety' => 'Bearded Splash',
		'variety' => 'Bearded White',
		'variety' => 'Beltsville Small White',
		'variety' => 'Birchen',
		'variety' => 'Black',
		'variety' => 'Black Frizzle',
		'variety' => 'Black & White',
		'variety' => 'Black Breasted Red',
		'variety' => 'Black Tailed Buff',
		'variety' => 'Black Tailed Red',
		'variety' => 'Blue',
		'variety' => 'Blue & White',
		'variety' => 'Blue Brassy Back',
		'variety' => 'Blue Breasted Red',
		'variety' => 'Blue Cream Light Brown',
		'variety' => 'Blue Golden Duckwing',
		'variety' => 'Blue Laced Red',
		'variety' => 'Blue Light Brown Dutch',
		'variety' => 'Blue Silver Duckwing',
		'variety' => 'Blue Wheaten',
		'variety' => 'Bourbon Red',
		'variety' => 'Butterscotch',
		'variety' => 'Brassy Back',
		'variety' => 'Bronze',
		'variety' => 'Brown',
		'variety' => 'Brown Red',
		'variety' => 'Buff',
		'variety' => 'Buff Columbian',
		'variety' => 'Chocolate',
		'variety' => 'Colored',
		'variety' => 'Columbian',
		'variety' => 'Cream Light Brown',
		'variety' => 'Crele',
		'variety' => 'Cuckoo',
		'variety' => 'Cumberland Blue',
		'variety' => 'Dark',
		'variety' => 'Dark Brown',
		'variety' => 'Eastern',
		'variety' => 'Fawn & White',
		'variety' => 'Fawn Silver Duckwing',
		'variety' => 'Ginger Red',
		'variety' => 'Golden',
		'variety' => 'Golden Duckwing',
		'variety' => 'Golden Penciled',
		'variety' => 'Golden Laced',
		'variety' => 'Golden Spangled',
		'variety' => 'Gray',
		'variety' => 'Khaki',
		'variety' => 'Lavender',
		'variety' => 'Lemon Blue',
		'variety' => 'Light',
		'variety' => 'Light Brown',
		'variety' => 'Partridge',
		'variety' => 'Pastel',
		'variety' => 'Pearl',
		'variety' => 'Penciled',
		'variety' => 'Porcelain',
		'variety' => 'Narragansett',
		'variety' => 'Mille Fleur',
		'variety' => 'Mottled',
		'variety' => 'Non Bearded Black',
		'variety' => 'Non Bearded Blue',
		'variety' => 'Non Bearded Buff',
		'variety' => 'Non Bearded Buff Laced',
		'variety' => 'Non Bearded Gray',
		'variety' => 'Non Bearded Golden',
		'variety' => 'Non Bearded Partridge',
		'variety' => 'Non Bearded Silver',
		'variety' => 'Non Bearded White',
		'variety' => 'Non Bearded White Crested Black',
		'variety' => 'Non Bearded White Crested Blue',
		'variety' => 'Non Bearded Black Crested White',
		'variety' => 'Quail',
		'variety' => 'Red',
		'variety' => 'Red Pyle',
		'variety' => 'Red Shouldered',
		'variety' => 'Rose Comb',
		'variety' => 'Rose Comb Black',
		'variety' => 'Rose Comb Buff',
		'variety' => 'Rose Comb Cuckoo',
		'variety' => 'Rose Comb Golden',
		'variety' => 'Rose Comb Silver',
		'variety' => 'Rose Comb White',
		'variety' => 'Royal Palm',
		'variety' => 'Saddleback',
		'variety' => 'Salmon',
		'variety' => 'Self Blue',
		'variety' => 'Sex Linked',
		'variety' => 'Silver',
		'variety' => 'Silver Blue',
		'variety' => 'Silver Duckwing',
		'variety' => 'Silver Gray',
		'variety' => 'Silver Laced',
		'variety' => 'Silver Penciled',
		'variety' => 'Silver Spangled',
		'variety' => 'Single Comb',
		'variety' => 'Single Comb Black',
		'variety' => 'Single Comb Black Tailed Red';
		'variety' => 'Single Comb Buff',
		'variety' => 'Single Comb Columbian',
		'variety' => 'Single Comb Cuckoo',
		'variety' => 'Single Comb Dark Brown',
		'variety' => 'Single Comb Light Brown',
		'variety' => 'Single Comb Red',
		'variety' => 'Single Comb Silver',
		'variety' => 'Slate',
		'variety' => 'Snowy',
		'variety' => 'Speckled',
		'variety' => 'Tufted',
		'variety' => 'Wheaten',
		'variety' => 'White',
		'variety' => 'White Holland',
		'variety' => 'White Laced Red',
        ]);
    }
}
